In [21]:
import pandas as pd

In [22]:
df = pd.read_csv("cleaned_data.csv")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient name    1000 non-null   object
 1   Age             1000 non-null   float64
 2   Gender          1000 non-null   object
 3   Condition       794 non-null    object
 4   Medication      1000 non-null   object
 5   Visit date      1000 non-null   object
 6   Blood pressure  1000 non-null   object
 7   Cholesterol     1000 non-null   float64
 8   Email           1000 non-null   object
 9   Phone number    1000 non-null   object
 10  Systolic        1000 non-null   float64
 11  Diastolic       1000 non-null   float64
dtypes: float64(4), object(8)
memory usage: 93.9+ KB

In [24]:
df.head()

,Patient name,Age,Gender,Condition,Medication,Visit date,Blood pressure,Cholesterol,Email,Phone number,Systolic,Diastolic
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555,140.0,90.0
1,Emily Davis,40.0,Male,Diabetes,No_Medication,2018-04-05,120/80,200.0,Unknown,Unknown,120.0,80.0
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,Unknown,110.0,70.0
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,180.0,name@hospital.org,555-555-5555,110.0,70.0
4,David Lee,40.0,Female,Asthma,No_Medication,2020-02-20,110/70,180.0,Unknown,,110.0,70.0

In [30]:
df = df.dropna(subset=["Condition"])

In [31]:
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})
df = pd.get_dummies(df, columns=["Medication"], drop_first=True)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 794 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       794 non-null    float64
 1   Gender                    551 non-null    float64
 2   Condition                 794 non-null    object
 3   Visit date                794 non-null    object
 4   Blood pressure            794 non-null    object
 5   Cholesterol               794 non-null    float64
 6   Systolic                  794 non-null    float64
 7   Diastolic                 794 non-null    float64
 8   Medication_ATORVASTATIN   794 non-null    bool
 9   Medication_LISINOPRIL     794 non-null    bool
 10  Medication_METFORMIN      794 non-null    bool
 11  Medication_No_Medication  794 non-null    bool
dtypes: bool(4), float64(5), object(3)
memory usage: 58.9+ KB

In [33]:
df["Visit Date"] = pd.to_datetime(df["Visit date"])

df = df.drop(columns=["Visit Date"])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 794 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       794 non-null    float64
 1   Gender                    551 non-null    float64
 2   Condition                 794 non-null    object
 3   Visit date                794 non-null    object
 4   Blood pressure            794 non-null    object
 5   Cholesterol               794 non-null    float64
 6   Systolic                  794 non-null    float64
 7   Diastolic                 794 non-null    float64
 8   Medication_ATORVASTATIN   794 non-null    bool
 9   Medication_LISINOPRIL     794 non-null    bool
 10  Medication_METFORMIN      794 non-null    bool
 11  Medication_No_Medication  794 non-null    bool
dtypes: bool(4), float64(5), object(3)
memory usage: 58.9+ KB

In [35]:
df.shape

(794, 12)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 794 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       794 non-null    float64
 1   Gender                    551 non-null    float64
 2   Condition                 794 non-null    object
 3   Visit date                794 non-null    object
 4   Blood pressure            794 non-null    object
 5   Cholesterol               794 non-null    float64
 6   Systolic                  794 non-null    float64
 7   Diastolic                 794 non-null    float64
 8   Medication_ATORVASTATIN   794 non-null    bool
 9   Medication_LISINOPRIL     794 non-null    bool
 10  Medication_METFORMIN      794 non-null    bool
 11  Medication_No_Medication  794 non-null    bool
dtypes: bool(4), float64(5), object(3)
memory usage: 58.9+ KB

In [37]:
df.isnull().sum()

Age                           0
Gender                      243
Condition                     0
Visit date                    0
Blood pressure                0
Cholesterol                   0
Systolic                      0
Diastolic                     0
Medication_ATORVASTATIN       0
Medication_LISINOPRIL         0
Medication_METFORMIN          0
Medication_No_Medication      0
dtype: int64

In [38]:
df.head()

,Age,Gender,Condition,Visit date,Blood pressure,Cholesterol,Systolic,Diastolic,Medication_ATORVASTATIN,Medication_LISINOPRIL,Medication_METFORMIN,Medication_No_Medication
0,25.0,NaN,Heart Disease,2020-01-15,140/90,200.0,140.0,90.0,False,False,True,False
1,40.0,0.0,Diabetes,2018-04-05,120/80,200.0,120.0,80.0,False,False,False,True
2,35.0,NaN,Asthma,2019-12-01,110/70,160.0,110.0,70.0,False,False,True,False
3,40.0,0.0,Diabetes,2020-01-15,110/70,180.0,110.0,70.0,False,False,False,False
4,40.0,1.0,Asthma,2020-02-20,110/70,180.0,110.0,70.0,False,False,False,True

In [39]:
df["Condition"].value_counts()

Condition
Asthma           211
Heart Disease    207
Diabetes         205
Hypertension     171
Name: count, dtype: int64

In [40]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [41]:
df.isnull().sum()

Age                         0
Gender                      0
Condition                   0
Visit date                  0
Blood pressure              0
Cholesterol                 0
Systolic                    0
Diastolic                   0
Medication_ATORVASTATIN     0
Medication_LISINOPRIL       0
Medication_METFORMIN        0
Medication_No_Medication    0
dtype: int64

In [42]:
df = df.drop(columns=["Blood pressure"])

In [43]:
df.isnull().sum()

Age                         0
Gender                      0
Condition                   0
Visit date                  0
Cholesterol                 0
Systolic                    0
Diastolic                   0
Medication_ATORVASTATIN     0
Medication_LISINOPRIL       0
Medication_METFORMIN        0
Medication_No_Medication    0
dtype: int64

In [44]:

df.shape

(794, 11)

In [45]:
X = df.drop("Condition", axis=1)
y = df["Condition"]

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [47]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [48]:
df["Gender"] = df["Gender"].fillna("Other")

In [49]:
df.shape

(794, 11)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 794 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       794 non-null    float64
 1   Gender                    794 non-null    float64
 2   Condition                 794 non-null    object
 3   Visit date                794 non-null    object
 4   Cholesterol               794 non-null    float64
 5   Systolic                  794 non-null    float64
 6   Diastolic                 794 non-null    float64
 7   Medication_ATORVASTATIN   794 non-null    bool
 8   Medication_LISINOPRIL     794 non-null    bool
 9   Medication_METFORMIN      794 non-null    bool
 10  Medication_No_Medication  794 non-null    bool
dtypes: bool(4), float64(5), object(2)
memory usage: 52.7+ KB

In [51]:
df.isnull().sum()

Age                         0
Gender                      0
Condition                   0
Visit date                  0
Cholesterol                 0
Systolic                    0
Diastolic                   0
Medication_ATORVASTATIN     0
Medication_LISINOPRIL       0
Medication_METFORMIN        0
Medication_No_Medication    0
dtype: int64

In [52]:
df.head()

,Age,Gender,Condition,Visit date,Cholesterol,Systolic,Diastolic,Medication_ATORVASTATIN,Medication_LISINOPRIL,Medication_METFORMIN,Medication_No_Medication
0,25.0,0.0,Heart Disease,2020-01-15,200.0,140.0,90.0,False,False,True,False
1,40.0,0.0,Diabetes,2018-04-05,200.0,120.0,80.0,False,False,False,True
2,35.0,0.0,Asthma,2019-12-01,160.0,110.0,70.0,False,False,True,False
3,40.0,0.0,Diabetes,2020-01-15,180.0,110.0,70.0,False,False,False,False
4,40.0,1.0,Asthma,2020-02-20,180.0,110.0,70.0,False,False,False,True

In [53]:
df["Gender"].value_counts()

Gender
0.0    520
1.0    274
Name: count, dtype: int64

In [54]:
 import pandas as pd

df = pd.read_csv("cleaned_data.csv")

In [55]:
print(df.isnull().sum())

Patient name        0
Age                 0
Gender              0
Condition         206
Medication          0
Visit date          0
Blood pressure      0
Cholesterol         0
Email               0
Phone number        0
Systolic            0
Diastolic           0
dtype: int64

In [56]:
df = df.dropna(subset=["Condition"])

In [57]:
print(df["Condition"].isnull().sum())

0

In [58]:
df = df.drop(["Patient name", "Email", "Phone number"], axis=1)

In [59]:
df = df.drop("Visit date", axis=1)

In [60]:
df = pd.get_dummies(df, columns=["Medication"], drop_first=True)

In [67]:
import pandas as pd

df = pd.read_csv("cleaned_data.csv")

# 1. Remove rows with missing target
df = df.dropna(subset=["Condition"])

# 2. Drop useless columns
df = df.drop(["Patient name", "Email", "Phone number", "Visit date"], axis=1)

# 3. Separate FIRST (before encoding!)
X = df.drop("Condition", axis=1)
y = df["Condition"]

# 4. Encode ONLY features
X = pd.get_dummies(X, drop_first=True)

# 5. Train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 6. Train
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [64]:
import os
print(os.listdir())

['.git', '.ipynb_checkpoints', 'anaconda_projects', 'classification.ipynb', 'cleaned_data.csv', 'clustering.ipynb', 'healthcare.ipynb', 'messy_data.csv', 'Untitled.ipynb']

In [66]:
print(df.isnull().sum())

Age                         0
Cholesterol                 0
Systolic                    0
Diastolic                   0
Gender_Male                 0
Gender_Other                0
Condition_Diabetes          0
Condition_Heart Disease     0
Condition_Hypertension      0
Medication_ATORVASTATIN     0
Medication_LISINOPRIL       0
Medication_METFORMIN        0
Medication_No_Medication    0
Blood pressure_120/80       0
Blood pressure_130/85       0
Blood pressure_140/90       0
dtype: int64

In [68]:
y_pred = model.predict(X_test)

In [69]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.20754716981132076

In [70]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[10 13 12  1]
 [19 13  7  3]
 [22 15  8  2]
 [17  9  6  2]]

In [71]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

               precision    recall  f1-score   support

       Asthma       0.15      0.28      0.19        36
     Diabetes       0.26      0.31      0.28        42
Heart Disease       0.24      0.17      0.20        47
 Hypertension       0.25      0.06      0.10        34

     accuracy                           0.21       159
    macro avg       0.22      0.20      0.19       159
 weighted avg       0.23      0.21      0.20       159

In [72]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', RandomForestClassifier(n_estimators=200, random_state=42))
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

In [73]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.3333333333333333