In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_data.csv")

In [3]:
df.head()

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number,systolic,diastolic
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555,140.0,90.0
1,Emily Davis,40.0,Male,Diabetes,No_Medication,2018-04-05,120/80,200.0,Unknown,Unknown,120.0,80.0
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,Unknown,110.0,70.0
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,180.0,name@hospital.org,555-555-5555,110.0,70.0
4,David Lee,40.0,Female,Asthma,No_Medication,2020-02-20,110/70,180.0,Unknown,,110.0,70.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient Name    1000 non-null   object
 1   Age             1000 non-null   float64
 2   Gender          1000 non-null   object
 3   Condition       794 non-null    object
 4   Medication      1000 non-null   object
 5   Visit Date      1000 non-null   object
 6   Blood Pressure  1000 non-null   object
 7   Cholesterol     1000 non-null   float64
 8   Email           1000 non-null   object
 9   Phone Number    1000 non-null   object
 10  systolic        1000 non-null   float64
 11  diastolic       1000 non-null   float64
dtypes: float64(4), object(8)
memory usage: 93.9+ KB

In [5]:
df = df.drop(columns=["Patient Name", "Email", "Phone Number"])

In [6]:
df = df.dropna(subset=["Condition"])

In [7]:
df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})
df = pd.get_dummies(df, columns=["Medication"], drop_first=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 794 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       794 non-null    float64
 1   Gender                    551 non-null    float64
 2   Condition                 794 non-null    object
 3   Visit Date                794 non-null    object
 4   Blood Pressure            794 non-null    object
 5   Cholesterol               794 non-null    float64
 6   systolic                  794 non-null    float64
 7   diastolic                 794 non-null    float64
 8   Medication_ATORVASTATIN   794 non-null    bool
 9   Medication_LISINOPRIL     794 non-null    bool
 10  Medication_METFORMIN      794 non-null    bool
 11  Medication_No_Medication  794 non-null    bool
dtypes: bool(4), float64(5), object(3)
memory usage: 58.9+ KB

In [9]:
df["Visit Date"] = pd.to_datetime(df["Visit Date"])
df["Visit_Year"] = df["Visit Date"].dt.year
df["Visit_Month"] = df["Visit Date"].dt.month

df = df.drop(columns=["Visit Date"])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 794 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       794 non-null    float64
 1   Gender                    551 non-null    float64
 2   Condition                 794 non-null    object
 3   Blood Pressure            794 non-null    object
 4   Cholesterol               794 non-null    float64
 5   systolic                  794 non-null    float64
 6   diastolic                 794 non-null    float64
 7   Medication_ATORVASTATIN   794 non-null    bool
 8   Medication_LISINOPRIL     794 non-null    bool
 9   Medication_METFORMIN      794 non-null    bool
 10  Medication_No_Medication  794 non-null    bool
 11  Visit_Year                794 non-null    int32
 12  Visit_Month               794 non-null    int32
dtypes: bool(4), float64(5), int32(2), object(2)
memory usage: 58.9+ KB

In [11]:
df.shape

(794, 13)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 794 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       794 non-null    float64
 1   Gender                    551 non-null    float64
 2   Condition                 794 non-null    object
 3   Blood Pressure            794 non-null    object
 4   Cholesterol               794 non-null    float64
 5   systolic                  794 non-null    float64
 6   diastolic                 794 non-null    float64
 7   Medication_ATORVASTATIN   794 non-null    bool
 8   Medication_LISINOPRIL     794 non-null    bool
 9   Medication_METFORMIN      794 non-null    bool
 10  Medication_No_Medication  794 non-null    bool
 11  Visit_Year                794 non-null    int32
 12  Visit_Month               794 non-null    int32
dtypes: bool(4), float64(5), int32(2), object(2)
memory usage: 58.9+ KB

In [13]:
df.isnull().sum()

Age                           0
Gender                      243
Condition                     0
Blood Pressure                0
Cholesterol                   0
systolic                      0
diastolic                     0
Medication_ATORVASTATIN       0
Medication_LISINOPRIL         0
Medication_METFORMIN          0
Medication_No_Medication      0
Visit_Year                    0
Visit_Month                   0
dtype: int64

In [14]:
df.head()

,Age,Gender,Condition,Blood Pressure,Cholesterol,systolic,diastolic,Medication_ATORVASTATIN,Medication_LISINOPRIL,Medication_METFORMIN,Medication_No_Medication,Visit_Year,Visit_Month
0,25.0,NaN,Heart Disease,140/90,200.0,140.0,90.0,False,False,True,False,2020,1
1,40.0,0.0,Diabetes,120/80,200.0,120.0,80.0,False,False,False,True,2018,4
2,35.0,NaN,Asthma,110/70,160.0,110.0,70.0,False,False,True,False,2019,12
3,40.0,0.0,Diabetes,110/70,180.0,110.0,70.0,False,False,False,False,2020,1
4,40.0,1.0,Asthma,110/70,180.0,110.0,70.0,False,False,False,True,2020,2

In [15]:
df["Condition"].value_counts()

Condition
Asthma           211
Heart Disease    207
Diabetes         205
Hypertension     171
Name: count, dtype: int64

In [16]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [17]:
df.isnull().sum()

Age                         0
Gender                      0
Condition                   0
Blood Pressure              0
Cholesterol                 0
systolic                    0
diastolic                   0
Medication_ATORVASTATIN     0
Medication_LISINOPRIL       0
Medication_METFORMIN        0
Medication_No_Medication    0
Visit_Year                  0
Visit_Month                 0
dtype: int64

In [18]:
df = df.drop(columns=["Blood Pressure"])

In [19]:
df.isnull().sum()

Age                         0
Gender                      0
Condition                   0
Cholesterol                 0
systolic                    0
diastolic                   0
Medication_ATORVASTATIN     0
Medication_LISINOPRIL       0
Medication_METFORMIN        0
Medication_No_Medication    0
Visit_Year                  0
Visit_Month                 0
dtype: int64

In [20]:

df.shape

(794, 12)

In [23]:
X = df.drop("Condition", axis=1)
y = df["Condition"]

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [25]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [26]:
df["Gender"] = df["Gender"].fillna("Other")

In [27]:
df.shape

(794, 12)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 794 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       794 non-null    float64
 1   Gender                    794 non-null    float64
 2   Condition                 794 non-null    object
 3   Cholesterol               794 non-null    float64
 4   systolic                  794 non-null    float64
 5   diastolic                 794 non-null    float64
 6   Medication_ATORVASTATIN   794 non-null    bool
 7   Medication_LISINOPRIL     794 non-null    bool
 8   Medication_METFORMIN      794 non-null    bool
 9   Medication_No_Medication  794 non-null    bool
 10  Visit_Year                794 non-null    int32
 11  Visit_Month               794 non-null    int32
dtypes: bool(4), float64(5), int32(2), object(1)
memory usage: 52.7+ KB

In [29]:
df.isnull().sum()

Age                         0
Gender                      0
Condition                   0
Cholesterol                 0
systolic                    0
diastolic                   0
Medication_ATORVASTATIN     0
Medication_LISINOPRIL       0
Medication_METFORMIN        0
Medication_No_Medication    0
Visit_Year                  0
Visit_Month                 0
dtype: int64

In [30]:
df.head()

,Age,Gender,Condition,Cholesterol,systolic,diastolic,Medication_ATORVASTATIN,Medication_LISINOPRIL,Medication_METFORMIN,Medication_No_Medication,Visit_Year,Visit_Month
0,25.0,0.0,Heart Disease,200.0,140.0,90.0,False,False,True,False,2020,1
1,40.0,0.0,Diabetes,200.0,120.0,80.0,False,False,False,True,2018,4
2,35.0,0.0,Asthma,160.0,110.0,70.0,False,False,True,False,2019,12
3,40.0,0.0,Diabetes,180.0,110.0,70.0,False,False,False,False,2020,1
4,40.0,1.0,Asthma,180.0,110.0,70.0,False,False,False,True,2020,2

In [31]:
df["Gender"].value_counts()

Gender
0.0    520
1.0    274
Name: count, dtype: int64