In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_data.csv")

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_name             20 non-null     object
 1   age                      20 non-null     int64
 2   gender                   15 non-null     float64
 3   condition                20 non-null     object
 4   cholesterol              20 non-null     float64
 5   systolic                 20 non-null     float64
 6   diastolic                20 non-null     float64
 7   medication_ATORVASTATIN  20 non-null     bool
 8   medication_LISINOPRIL    20 non-null     bool
 9   medication_METFORMIN     20 non-null     bool
 10  medication_NONE          20 non-null     bool
dtypes: bool(4), float64(4), int64(1), object(2)
memory usage: 1.3+ KB

In [25]:
df.head()

,patient_name,age,gender,condition,cholesterol,systolic,diastolic,medication_ATORVASTATIN,medication_LISINOPRIL,medication_METFORMIN,medication_NONE
0,david lee,25,NaN,Heart Disease,200.0,140.0,90.0,False,False,True,False
1,emily davis,35,NaN,Diabetes,200.0,120.0,80.0,False,False,False,True
2,laura martinez,35,NaN,Asthma,160.0,110.0,70.0,False,False,True,False
3,michael wilson,35,NaN,Diabetes,200.0,110.0,70.0,False,False,False,False
4,david lee,35,NaN,Asthma,180.0,110.0,70.0,False,False,False,True

In [ ]:
X = df.drop("condition", axis=1)
y = df["Condition"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [11]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

KeyError: 'Gender'

In [12]:
df["Gender"] = df["Gender"].fillna("Other")

KeyError: 'Gender'

In [13]:
df.shape

(20, 10)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_name  20 non-null     object
 1   age           20 non-null     int64
 2   gender        20 non-null     object
 3   condition     20 non-null     object
 4   medication    20 non-null     object
 5   cholesterol   20 non-null     float64
 6   systolic      20 non-null     float64
 7   diastolic     20 non-null     float64
 8   visit_year    20 non-null     float64
 9   visit_month   20 non-null     float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.7+ KB

In [15]:
df.isnull().sum()

patient_name    0
age             0
gender          0
condition       0
medication      0
cholesterol     0
systolic        0
diastolic       0
visit_year      0
visit_month     0
dtype: int64

In [16]:
df.head()

,patient_name,age,gender,condition,medication,cholesterol,systolic,diastolic,visit_year,visit_month
0,david lee,25,other,Heart Disease,METFORMIN,200.0,140.0,90.0,2020.0,1.0
1,emily davis,35,male,Diabetes,NONE,200.0,120.0,80.0,2020.0,1.0
2,laura martinez,35,other,Asthma,METFORMIN,160.0,110.0,70.0,2020.0,1.0
3,michael wilson,35,male,Diabetes,ALBUTEROL,200.0,110.0,70.0,2020.0,1.0
4,david lee,35,female,Asthma,NONE,180.0,110.0,70.0,2020.0,1.0

In [17]:
df["Gender"].value_counts()

KeyError: 'Gender'