In [ ]:
pip install numpy pandas scikit-learn

In [2]:
pip install scipy

Requirement already satisfied: scipy in c:\users\gauta\anaconda3\envs\venv\lib\site-packages (1.15.3)
Requirement already satisfied: numpy<2.5,>=1.23.5 in c:\users\gauta\anaconda3\envs\venv\lib\site-packages (from scipy) (2.2.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_csv = pd.read_csv("messy_data.csv")

In [4]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,david lee,25,Other,Heart Disease,METFORMIN,01/15/2020,140/90,200.0,name@hospital.org,555-555-5555
1,emily davis,NaN,Male,Diabetes,NONE,"April 5, 2018",120/80,200.0,NaN,NaN
2,laura martinez,35,Other,Asthma,METFORMIN,2019.12.01,110/70,160.0,contact@domain.com,NaN
3,michael wilson,NaN,Male,Diabetes,ALBUTEROL,01/15/2020,110/70,NaN,name@hospital.org,555-555-5555
4,david lee,NaN,Female,Asthma,NONE,2020/02/20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,mary clark,70,Other,Asthma,ALBUTEROL,03-25-2019,110/70,NaN,name@hospital.org,NaN
996,mary clark,forty,Other,NaN,LISINOPRIL,01/15/2020,NaN,160.0,NaN,123-456-7890
997,laura martinez,forty,Other,NaN,ALBUTEROL,2020/02/20,110/70,NaN,name@hospital.org,NaN
998,jane smith,25,Male,NaN,ALBUTEROL,"April 5, 2018",110/70,200.0,NaN,
999,james taylor,forty,Male,Diabetes,ATORVASTATIN,2020/02/20,120/80,220.0,NaN,123-456-7890

In [5]:
df_csv.info()
df_csv.isnull().sum()
df_csv.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient Name    1000 non-null   object
 1   Age             841 non-null    object
 2   Gender          1000 non-null   object
 3   Condition       794 non-null    object
 4   Medication      1000 non-null   object
 5   Visit Date      1000 non-null   object
 6   Blood Pressure  834 non-null    object
 7   Cholesterol     769 non-null    float64
 8   Email           616 non-null    object
 9   Phone Number    821 non-null    object
dtypes: float64(1), object(9)
memory usage: 78.2+ KB

np.int64(0)

In [6]:
df_csv['Patient Name'] = df_csv['Patient Name'].str.title()

In [7]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,David Lee,25,Other,Heart Disease,METFORMIN,01/15/2020,140/90,200.0,name@hospital.org,555-555-5555
1,Emily Davis,NaN,Male,Diabetes,NONE,"April 5, 2018",120/80,200.0,NaN,NaN
2,Laura Martinez,35,Other,Asthma,METFORMIN,2019.12.01,110/70,160.0,contact@domain.com,NaN
3,Michael Wilson,NaN,Male,Diabetes,ALBUTEROL,01/15/2020,110/70,NaN,name@hospital.org,555-555-5555
4,David Lee,NaN,Female,Asthma,NONE,2020/02/20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70,Other,Asthma,ALBUTEROL,03-25-2019,110/70,NaN,name@hospital.org,NaN
996,Mary Clark,forty,Other,NaN,LISINOPRIL,01/15/2020,NaN,160.0,NaN,123-456-7890
997,Laura Martinez,forty,Other,NaN,ALBUTEROL,2020/02/20,110/70,NaN,name@hospital.org,NaN
998,Jane Smith,25,Male,NaN,ALBUTEROL,"April 5, 2018",110/70,200.0,NaN,
999,James Taylor,forty,Male,Diabetes,ATORVASTATIN,2020/02/20,120/80,220.0,NaN,123-456-7890

In [8]:
pip install word2number

Requirement already satisfied: word2number in c:\users\gauta\anaconda3\envs\venv\lib\site-packages (1.1)
Note: you may need to restart the kernel to use updated packages.

In [9]:
from word2number import w2n
def convert_age(x):
    try:
        return int(x) 
    except:
        try:
            return w2n.word_to_num(x)  
        except:
            return None  

df_csv['Age'] = df_csv['Age'].apply(convert_age)

In [10]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,David Lee,25.0,Other,Heart Disease,METFORMIN,01/15/2020,140/90,200.0,name@hospital.org,555-555-5555
1,Emily Davis,NaN,Male,Diabetes,NONE,"April 5, 2018",120/80,200.0,NaN,NaN
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019.12.01,110/70,160.0,contact@domain.com,NaN
3,Michael Wilson,NaN,Male,Diabetes,ALBUTEROL,01/15/2020,110/70,NaN,name@hospital.org,555-555-5555
4,David Lee,NaN,Female,Asthma,NONE,2020/02/20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,03-25-2019,110/70,NaN,name@hospital.org,NaN
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,01/15/2020,NaN,160.0,NaN,123-456-7890
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020/02/20,110/70,NaN,name@hospital.org,NaN
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,"April 5, 2018",110/70,200.0,NaN,
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020/02/20,120/80,220.0,NaN,123-456-7890

In [11]:
df_csv['Age'] = df_csv['Age'].fillna(df_csv['Age'].median())

In [12]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,David Lee,25.0,Other,Heart Disease,METFORMIN,01/15/2020,140/90,200.0,name@hospital.org,555-555-5555
1,Emily Davis,40.0,Male,Diabetes,NONE,"April 5, 2018",120/80,200.0,NaN,NaN
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019.12.01,110/70,160.0,contact@domain.com,NaN
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,01/15/2020,110/70,NaN,name@hospital.org,555-555-5555
4,David Lee,40.0,Female,Asthma,NONE,2020/02/20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,03-25-2019,110/70,NaN,name@hospital.org,NaN
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,01/15/2020,NaN,160.0,NaN,123-456-7890
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020/02/20,110/70,NaN,name@hospital.org,NaN
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,"April 5, 2018",110/70,200.0,NaN,
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020/02/20,120/80,220.0,NaN,123-456-7890

In [13]:
df_csv.replace(["NaN", "none", "NONE", ""], np.nan, inplace=True)

In [14]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,David Lee,25.0,Other,Heart Disease,METFORMIN,01/15/2020,140/90,200.0,name@hospital.org,555-555-5555
1,Emily Davis,40.0,Male,Diabetes,NaN,"April 5, 2018",120/80,200.0,NaN,NaN
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019.12.01,110/70,160.0,contact@domain.com,NaN
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,01/15/2020,110/70,NaN,name@hospital.org,555-555-5555
4,David Lee,40.0,Female,Asthma,NaN,2020/02/20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,03-25-2019,110/70,NaN,name@hospital.org,NaN
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,01/15/2020,NaN,160.0,NaN,123-456-7890
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020/02/20,110/70,NaN,name@hospital.org,NaN
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,"April 5, 2018",110/70,200.0,NaN,
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020/02/20,120/80,220.0,NaN,123-456-7890

In [15]:
df_csv['Visit Date'] = df_csv['Visit Date'].astype(str).str.strip()

In [16]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,David Lee,25.0,Other,Heart Disease,METFORMIN,01/15/2020,140/90,200.0,name@hospital.org,555-555-5555
1,Emily Davis,40.0,Male,Diabetes,NaN,"April 5, 2018",120/80,200.0,NaN,NaN
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019.12.01,110/70,160.0,contact@domain.com,NaN
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,01/15/2020,110/70,NaN,name@hospital.org,555-555-5555
4,David Lee,40.0,Female,Asthma,NaN,2020/02/20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,03-25-2019,110/70,NaN,name@hospital.org,NaN
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,01/15/2020,NaN,160.0,NaN,123-456-7890
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020/02/20,110/70,NaN,name@hospital.org,NaN
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,"April 5, 2018",110/70,200.0,NaN,
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020/02/20,120/80,220.0,NaN,123-456-7890

In [17]:
df_csv['Visit Date'] = df_csv['Visit Date'].str.replace('.', '-', regex=False)

In [18]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,David Lee,25.0,Other,Heart Disease,METFORMIN,01/15/2020,140/90,200.0,name@hospital.org,555-555-5555
1,Emily Davis,40.0,Male,Diabetes,NaN,"April 5, 2018",120/80,200.0,NaN,NaN
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,NaN
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,01/15/2020,110/70,NaN,name@hospital.org,555-555-5555
4,David Lee,40.0,Female,Asthma,NaN,2020/02/20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,03-25-2019,110/70,NaN,name@hospital.org,NaN
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,01/15/2020,NaN,160.0,NaN,123-456-7890
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020/02/20,110/70,NaN,name@hospital.org,NaN
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,"April 5, 2018",110/70,200.0,NaN,
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020/02/20,120/80,220.0,NaN,123-456-7890

In [19]:
df_csv['Visit Date'] = pd.to_datetime(
    df_csv['Visit Date'],
    errors='coerce',
    format='mixed'
)

In [20]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555
1,Emily Davis,40.0,Male,Diabetes,NaN,2018-04-05,120/80,200.0,NaN,NaN
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,NaN
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,NaN,name@hospital.org,555-555-5555
4,David Lee,40.0,Female,Asthma,NaN,2020-02-20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,2019-03-25,110/70,NaN,name@hospital.org,NaN
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,2020-01-15,NaN,160.0,NaN,123-456-7890
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020-02-20,110/70,NaN,name@hospital.org,NaN
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,2018-04-05,110/70,200.0,NaN,
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020-02-20,120/80,220.0,NaN,123-456-7890

In [21]:
df_csv['Medication'] = df_csv['Medication'].replace(['NONE'], np.nan)
df_csv['Medication'] = df_csv['Medication'].fillna('No_Medication')

In [22]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555
1,Emily Davis,40.0,Male,Diabetes,No_Medication,2018-04-05,120/80,200.0,NaN,NaN
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,NaN
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,NaN,name@hospital.org,555-555-5555
4,David Lee,40.0,Female,Asthma,No_Medication,2020-02-20,110/70,180.0,NaN,
...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,2019-03-25,110/70,NaN,name@hospital.org,NaN
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,2020-01-15,NaN,160.0,NaN,123-456-7890
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020-02-20,110/70,NaN,name@hospital.org,NaN
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,2018-04-05,110/70,200.0,NaN,
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020-02-20,120/80,220.0,NaN,123-456-7890

In [23]:
df_csv[['systolic', 'diastolic']] = df_csv['Blood Pressure'].str.split('/', expand=True)

df_csv['systolic'] = pd.to_numeric(df_csv['systolic'], errors='coerce')
df_csv['diastolic'] = pd.to_numeric(df_csv['diastolic'], errors='coerce')

In [24]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number,systolic,diastolic
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555,140.0,90.0
1,Emily Davis,40.0,Male,Diabetes,No_Medication,2018-04-05,120/80,200.0,NaN,NaN,120.0,80.0
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,NaN,110.0,70.0
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,NaN,name@hospital.org,555-555-5555,110.0,70.0
4,David Lee,40.0,Female,Asthma,No_Medication,2020-02-20,110/70,180.0,NaN,,110.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,2019-03-25,110/70,NaN,name@hospital.org,NaN,110.0,70.0
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,2020-01-15,NaN,160.0,NaN,123-456-7890,NaN,NaN
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020-02-20,110/70,NaN,name@hospital.org,NaN,110.0,70.0
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,2018-04-05,110/70,200.0,NaN,,110.0,70.0
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020-02-20,120/80,220.0,NaN,123-456-7890,120.0,80.0

In [25]:
df_csv.fillna({
    'systolic': df_csv['systolic'].median(),
    'diastolic': df_csv['diastolic'].median()
}, inplace=True)

In [26]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number,systolic,diastolic
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555,140.0,90.0
1,Emily Davis,40.0,Male,Diabetes,No_Medication,2018-04-05,120/80,200.0,NaN,NaN,120.0,80.0
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,NaN,110.0,70.0
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,NaN,name@hospital.org,555-555-5555,110.0,70.0
4,David Lee,40.0,Female,Asthma,No_Medication,2020-02-20,110/70,180.0,NaN,,110.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,2019-03-25,110/70,NaN,name@hospital.org,NaN,110.0,70.0
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,2020-01-15,NaN,160.0,NaN,123-456-7890,130.0,85.0
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020-02-20,110/70,NaN,name@hospital.org,NaN,110.0,70.0
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,2018-04-05,110/70,200.0,NaN,,110.0,70.0
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020-02-20,120/80,220.0,NaN,123-456-7890,120.0,80.0

In [27]:
df_csv['Blood Pressure'] = df_csv['systolic'].astype(int).astype(str) + '/' + df_csv['diastolic'].astype(int).astype(str)

In [28]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number,systolic,diastolic
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555,140.0,90.0
1,Emily Davis,40.0,Male,Diabetes,No_Medication,2018-04-05,120/80,200.0,NaN,NaN,120.0,80.0
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,NaN,110.0,70.0
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,NaN,name@hospital.org,555-555-5555,110.0,70.0
4,David Lee,40.0,Female,Asthma,No_Medication,2020-02-20,110/70,180.0,NaN,,110.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,2019-03-25,110/70,NaN,name@hospital.org,NaN,110.0,70.0
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,2020-01-15,130/85,160.0,NaN,123-456-7890,130.0,85.0
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020-02-20,110/70,NaN,name@hospital.org,NaN,110.0,70.0
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,2018-04-05,110/70,200.0,NaN,,110.0,70.0
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020-02-20,120/80,220.0,NaN,123-456-7890,120.0,80.0

In [29]:
df_csv['Email'] = df_csv['Email'].fillna('Unknown')
df_csv['Phone Number'] = df_csv['Phone Number'].fillna('Unknown')

In [30]:
df_csv

,Patient Name,Age,Gender,Condition,Medication,Visit Date,Blood Pressure,Cholesterol,Email,Phone Number,systolic,diastolic
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555,140.0,90.0
1,Emily Davis,40.0,Male,Diabetes,No_Medication,2018-04-05,120/80,200.0,Unknown,Unknown,120.0,80.0
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,Unknown,110.0,70.0
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,NaN,name@hospital.org,555-555-5555,110.0,70.0
4,David Lee,40.0,Female,Asthma,No_Medication,2020-02-20,110/70,180.0,Unknown,,110.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,2019-03-25,110/70,NaN,name@hospital.org,Unknown,110.0,70.0
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,2020-01-15,130/85,160.0,Unknown,123-456-7890,130.0,85.0
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020-02-20,110/70,NaN,name@hospital.org,Unknown,110.0,70.0
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,2018-04-05,110/70,200.0,Unknown,,110.0,70.0
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020-02-20,120/80,220.0,Unknown,123-456-7890,120.0,80.0

In [31]:
df_csv['Cholesterol'] = pd.to_numeric(df_csv['Cholesterol'], errors='coerce')

In [32]:
print(df_csv['Cholesterol'].isna().sum())
print(df_csv['Cholesterol'].notna().sum())

231
769

In [33]:
print(df_csv['Cholesterol'].dtype)

float64

In [34]:
df_csv['Cholesterol'].describe()

count    769.00000
mean     189.23277
std       22.28039
min      160.00000
25%      160.00000
50%      180.00000
75%      200.00000
max      220.00000
Name: Cholesterol, dtype: float64

In [35]:
df_csv['Cholesterol'].isna().mean() * 100

np.float64(23.1)

In [35]:
df_csv['Cholesterol'] = df_csv['Cholesterol'].fillna(df_csv['Cholesterol'].median())

In [39]:
df_csv.columns = df_csv.columns.str.capitalize()

In [40]:
df_csv

,Patient name,Age,Gender,Condition,Medication,Visit date,Blood pressure,Cholesterol,Email,Phone number,Systolic,Diastolic
0,David Lee,25.0,Other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0,name@hospital.org,555-555-5555,140.0,90.0
1,Emily Davis,40.0,Male,Diabetes,No_Medication,2018-04-05,120/80,200.0,Unknown,Unknown,120.0,80.0
2,Laura Martinez,35.0,Other,Asthma,METFORMIN,2019-12-01,110/70,160.0,contact@domain.com,Unknown,110.0,70.0
3,Michael Wilson,40.0,Male,Diabetes,ALBUTEROL,2020-01-15,110/70,180.0,name@hospital.org,555-555-5555,110.0,70.0
4,David Lee,40.0,Female,Asthma,No_Medication,2020-02-20,110/70,180.0,Unknown,,110.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Mary Clark,70.0,Other,Asthma,ALBUTEROL,2019-03-25,110/70,180.0,name@hospital.org,Unknown,110.0,70.0
996,Mary Clark,40.0,Other,NaN,LISINOPRIL,2020-01-15,130/85,160.0,Unknown,123-456-7890,130.0,85.0
997,Laura Martinez,40.0,Other,NaN,ALBUTEROL,2020-02-20,110/70,180.0,name@hospital.org,Unknown,110.0,70.0
998,Jane Smith,25.0,Male,NaN,ALBUTEROL,2018-04-05,110/70,200.0,Unknown,,110.0,70.0
999,James Taylor,40.0,Male,Diabetes,ATORVASTATIN,2020-02-20,120/80,220.0,Unknown,123-456-7890,120.0,80.0

In [38]:
df_csv.to_csv("cleaned_data.csv", index=False)