In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/messy_data.csv")

In [4]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [5]:
df.replace(["Unknown", "", " "], np.nan, inplace=True)

In [6]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["age"] = df["age"].fillna(df["age"].median()) # nullable integer
df["age"] = df["age"].astype("Int64")  # nullable integer
df["visit_date"] = pd.to_datetime(df["visit_date"], errors="coerce")

In [7]:
df["gender"] = df["gender"].str.strip().str.lower()
df["medication"] = df["medication"].str.strip().str.upper()

In [8]:
df["medication"] = df["medication"].replace("NO_MEDICATION", np.nan)

In [9]:
df["condition"] = df["condition"].fillna(df["condition"].mode()[0])

In [10]:
df = df.drop_duplicates()

In [11]:
df["cholesterol"] = pd.to_numeric(df["cholesterol"], errors="coerce")

In [12]:
df.drop(columns=["email", "phone_number"], inplace=True, errors="ignore")

In [13]:
df.reset_index(drop=True, inplace=True)

In [14]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_name    1000 non-null   object
 1   age             1000 non-null   Int64
 2   gender          1000 non-null   object
 3   condition       1000 non-null   object
 4   medication      1000 non-null   object
 5   visit_date      183 non-null    datetime64[ns]
 6   blood_pressure  834 non-null    object
 7   cholesterol     769 non-null    float64
dtypes: Int64(1), datetime64[ns](1), float64(1), object(5)
memory usage: 63.6+ KB
None
       patient_name  age  gender      condition medication visit_date  \
0        david lee    25   other  Heart Disease  METFORMIN 2020-01-15
1      emily davis    35    male       Diabetes       NONE        NaT
2   laura martinez    35   other         Asthma  METFORMIN        NaT
3   michael wilson    35    male       Diabetes  ALBUTEROL 2020-01-15
4        david lee    35  female         Asthma       NONE        NaT

  blood_pressure  cholesterol
0         140/90        200.0
1         120/80        200.0
2         110/70        160.0
3         110/70          NaN
4         110/70        180.0

In [15]:
df

,patient_name,age,gender,condition,medication,visit_date,blood_pressure,cholesterol
0,david lee,25,other,Heart Disease,METFORMIN,2020-01-15,140/90,200.0
1,emily davis,35,male,Diabetes,NONE,NaT,120/80,200.0
2,laura martinez,35,other,Asthma,METFORMIN,NaT,110/70,160.0
3,michael wilson,35,male,Diabetes,ALBUTEROL,2020-01-15,110/70,NaN
4,david lee,35,female,Asthma,NONE,NaT,110/70,180.0
...,...,...,...,...,...,...,...,...
995,mary clark,70,other,Asthma,ALBUTEROL,NaT,110/70,NaN
996,mary clark,35,other,Asthma,LISINOPRIL,2020-01-15,NaN,160.0
997,laura martinez,35,other,Asthma,ALBUTEROL,NaT,110/70,NaN
998,jane smith,25,male,Asthma,ALBUTEROL,NaT,110/70,200.0
999,james taylor,35,male,Diabetes,ATORVASTATIN,NaT,120/80,220.0

In [16]:
df["systolic"] = df["blood_pressure"].str.split("/").str[0]
df["diastolic"] = df["blood_pressure"].str.split("/").str[1]

df["systolic"] = pd.to_numeric(df["systolic"], errors="coerce")
df["diastolic"] = pd.to_numeric(df["diastolic"], errors="coerce")

df["systolic"] = df["systolic"].fillna(df["systolic"].median())
df["diastolic"] = df["diastolic"].fillna(df["diastolic"].median())

df.drop(columns=["blood_pressure"], inplace=True)

In [17]:
df

,patient_name,age,gender,condition,medication,visit_date,cholesterol,systolic,diastolic
0,david lee,25,other,Heart Disease,METFORMIN,2020-01-15,200.0,140.0,90.0
1,emily davis,35,male,Diabetes,NONE,NaT,200.0,120.0,80.0
2,laura martinez,35,other,Asthma,METFORMIN,NaT,160.0,110.0,70.0
3,michael wilson,35,male,Diabetes,ALBUTEROL,2020-01-15,NaN,110.0,70.0
4,david lee,35,female,Asthma,NONE,NaT,180.0,110.0,70.0
...,...,...,...,...,...,...,...,...,...
995,mary clark,70,other,Asthma,ALBUTEROL,NaT,NaN,110.0,70.0
996,mary clark,35,other,Asthma,LISINOPRIL,2020-01-15,160.0,130.0,85.0
997,laura martinez,35,other,Asthma,ALBUTEROL,NaT,NaN,110.0,70.0
998,jane smith,25,male,Asthma,ALBUTEROL,NaT,200.0,110.0,70.0
999,james taylor,35,male,Diabetes,ATORVASTATIN,NaT,220.0,120.0,80.0

In [18]:
df["cholesterol"] = df["cholesterol"].fillna(df["cholesterol"].median())

In [19]:
df["visit_year"] = df["visit_date"].dt.year
df["visit_month"] = df["visit_date"].dt.month

df["visit_year"] = df["visit_year"].fillna(df["visit_year"].mode()[0])
df["visit_month"] = df["visit_month"].fillna(df["visit_month"].mode()[0])

In [21]:
df.to_csv('data/cleaned_data.csv', index=False)